name = "numex"
uuid = "a8200f4d-d47b-47ad-b386-b2a99d10126d"
authors = ["David Neilsen <david.neilsen@byu.edu> and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
